trigger:
- main

variables:
  imageName: SpringBootJava
  tag: $(Build.BuildId)

pool:
  name: Self_Managed

stages:
- stage: Build_Jar
  jobs:
  - template: templates/Jar_Build.yml

- stage: Build_Image
  dependsOn: Build_Jar
  jobs:
  - template: templates/Image_Build.yml
    parameters:
      imageName: $(imageName)
      tag: $(tag)

- stage: Publish
  dependsOn: Build_Image
  jobs:
  - job: PushImage
    steps:
    - script: |
        docker push $(imageName):$(tag)