trigger:
- main

variables:
  imageName: springbootapp
  tag: $(Build.BuildId)

pool:
  name: Self_Managed

stages:
- stage: Build_Jar
  jobs:
  - template: templates/Jar_Build.yml

- stage: Build_Image
  dependsOn: Build_Jar
  jobs:
  - template: templates/Image_Build.yml
    parameters:
      imageName: $(imageName)
      tag: $(tag)

- stage: Security_Scan
  dependsOn: Build_Image
  jobs:
  - template: templates/Trivy_Scan.yml
    parameters:
      imageName: $(imageName)
      tag: $(tag)

- stage: Publish
  dependsOn: Security_Scan
  jobs:
  - job: PushImage
    displayName: Push Docker Image

    steps:
    - script: |
        echo $(DOCKERHUB_PASSWORD) | docker login -u $(DOCKERHUB_USERNAME) --password-stdin
        docker push $(DOCKERHUB_USERNAME)/$(imageName):$(tag)

      displayName: Login and Push Image