trigger:
- main

variables:
  imageName: springbootapp
  tag: $(Build.BuildId)

pool:
  name: Self_Managed

stages:
- stage: Build_Jar
  jobs:
  - template: templates/Jar_Build.yml

- stage: Build_Image
  dependsOn: Build_Jar
  jobs:
  - template: templates/Image_Build.yml
    parameters:
      imageName: $(imageName)
      tag: $(tag)

# - stage: Security_Scan
#   dependsOn: Build_Image
#   jobs:
#   - template: templates/Trivy_Scan.yml
#     parameters:
#       imageName: $(imageName)
#       tag: $(tag)

- stage: Publish
  dependsOn: Build_Image
  jobs:
  - job: PushImage
    steps:
    - task: Docker@2
      displayName: 'Login and Push Docker Image'
      inputs:
        containerRegistry: 'Dockerhub'  # Name of the service connection
        repository: 'moshibl/springbootapp'    # DockerHub repo
        command: 'push'
        # tags: '$(tag)'