parameters:
  imageName: ''
  tag: ''

jobs:
- job: TrivyScan
  displayName: Security Scan

  steps:
  - script: |
      mkdir -p /azp/_work/1/a/trivy

      docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /azp/_work/1/a/trivy:/report \
        aquasec/trivy image \
        --severity HIGH,CRITICAL \
        --format json \
        --output /report/trivy-report.json \
        --timeout 10m \
        ${{ parameters.imageName }}:${{ parameters.tag }}

      VULN_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH" or .Severity=="CRITICAL")] | length' $(Build.ArtifactStagingDirectory)/trivy/trivy-report.json)
      echo "Number of HIGH/CRITICAL vulnerabilities: $VULN_COUNT"

      if [ "$VULN_COUNT" -gt 0 ]; then
        echo "❌ High/critical vulnerabilities found. Failing pipeline."
        exit 1
      else
        echo "✅ No HIGH/CRITICAL vulnerabilities found."
      fi
    displayName: Run Trivy Scan and Enforce Quality Gate

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/trivy/trivy-report.json'
      artifact: 'TrivyScanReport'
      publishLocation: 'pipeline'